### ISSUE TITLE
.NET Core, Linux and Docker

### ISSUE THREAD

**Issue by rbanks54** [rbanks54/microcafe#3]
Port code to .NET core, deploy to Linux based containers.
Use dockerised versions of RabbitMq and Redis as well

**Comment by dasiths** [comment]
I implemented the Apply() on Aggregate a bit differently because the old version of .NET CORE didn't support dynamics.

See the [InternalEventHandler] method attribute:
https://github.com/dasiths/NEventLite/blob/master/src/Examples/NEventLite%20Example/Domain/Note.cs

My Aggregate is as follows:
https://github.com/dasiths/NEventLite/blob/master/src/Framework/Domain/AggregateRoot.cs

I have this wiring up the methods:
        private void SetupInternalEventHandlers()
        {
            _eventHandlerCache = ReflectionHelper.FindEventHandlerMethodsInAggregate(this.GetType());
        }

I believe the method marker also makes it easier to read the code in the aggregate. What are your thoughts?

**Comment by rbanks54** [comment]
Closing this and separating things out to separate issues
